apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-ip-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-ip-app
  template:
    metadata:
      labels:
        app: reverse-ip-app
    spec:
      containers:
      - name: reverse-ip-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080

