name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Docker installation
        run: |
          docker --version
          docker info

      - name: List directory contents
        run: ls -la

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        continue-on-error: true

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/reverse-ip-app:v1 .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/reverse-ip-app:v1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install reverse-ip-app ./reverse-ip-chart
