name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx for multi-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Log in to Docker Hub using GitHub Secrets for credentials
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 4: Build, tag, and push the Docker image
    - name: Build, tag, and push Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/reverse-ip-app:v1 --push .

  # Deploy job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the code (required by the Helm chart or other scripts)
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up kubectl by configuring access to the AWS EKS cluster
    - name: Set up kubectl
      run: |
        aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

    # Step 3: Deploy the Docker image to the Kubernetes cluster using Helm
    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install reverse-ip-app ./reverse-ip-chart
