name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Log in to Docker Hub using GitHub Secrets for credentials
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 3: Build and tag the Docker image
    - name: Build and tag Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/reverse-ip-app:v1 .

    # Step 4: Push the image to Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/reverse-ip-app:v1

  # Deploy job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the code (required by the Helm chart or other scripts)
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up kubectl by configuring access to the AWS EKS cluster
    - name: Set up kubectl
      run: |
        aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

    # Step 3: Deploy the Docker image to the Kubernetes cluster using Helm
    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install reverse-ip-app ./reverse-ip-chart
